@host=http://localhost:3000

POST {{host}}/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "username":"sorabh86",
    "email":"sorabh86@gmail.com",
    "password":"12345"
}

###

POST {{host}}/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "username":"neeraj",
    "password":"12345"
}